version: '3.1'
services:
  web:
    image: odoo:latest
    platform: linux/amd64
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
    environment:
      - HOST=db
      - USER=${POSTGRES_USER}
      - PASSWORD=${POSTGRES_PASSWORD}
    labels:
      - traefik.http.routers.odoo-instance.rule=Host(`${ODOO_URL}`)
      - traefik.port=8069
    networks:
      - web
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    labels:
      - traefik.enable=false
    networks:
      - web
volumes:
  odoo-web-data:
  odoo-db-data:
networks:
  web: